{
 "title": "ft_transcendence",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Request rate total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_count{job=\"backend\"}[1m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Memory usage",
   "type": "timeseries",
   "description": "Repérer une fuite mémoire - courbe doit montrer sans redescendre",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "p95 latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95,\n  sum by (le) (rate(http_request_duration_seconds_bucket{job=\"backend\"}[5m]))\n)\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{job=\"backend\"}[2m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg response time",
   "type": "timeseries",
   "description": "Temps moyen de reponse ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{job=\"backend\"}[5m]))\n/\nsum(rate(http_request_duration_seconds_count{job=\"backend\"}[5m]))\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Backend Health",
   "type": "timeseries",
   "description": "Etat de scrape Prometheus - 1 = ok",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "up{job=\"backend\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}