FROM prom/prometheus:v2.53.0

# Installer OpenSSL pour générer les certificats
USER root
RUN apt-get update && apt-get install -y openssl

# Créer le répertoire pour les certificats
RUN mkdir -p /etc/prometheus/certs

# Générer un certificat auto-signé
RUN openssl req -x509 -newkey rsa:4096 -keyout /etc/prometheus/certs/prometheus.key \
    -out /etc/prometheus/certs/prometheus.crt -days 365 -nodes \
    -subj "/CN=localhost"

COPY prometheus.yml /etc/prometheus/prometheus.yml
COPY rules.yml /etc/prometheus/rules.yml

USER nobody

ENTRYPOINT [ "/bin/prometheus", \
             "--config.file=/etc/prometheus/prometheus.yml", \
             "--storage.tsdb.path=/prometheus", \
             "--web.console.libraries=/usr/share/prometheus/console_libraries", \
             "--web.console.templates=/usr/share/prometheus/consoles", \
             "--web.listen-address=:9090", \
             "--web.ssl-cert-file=/etc/prometheus/certs/prometheus.crt", \
             "--web.ssl-key-file=/etc/prometheus/certs/prometheus.key" ]
