// Export all pages
export * from './home.js';
export * from './login.js';
export * from './signup.js';
export * from './classic.js';
export * from './tournament.js';
export * from './tournamentTransition.js';
export * from './victory.js';
export * from './game.js';
export * from './online.js';
export * from './profile.js';
export * from './friends.js';
export * from './friendsProfile.js';
export * from './friendRequests.js';
